### ISSUE TITLE
Allow Multiple Queries Per File

### ISSUE THREAD

**Issue by elithrar** [smotes/purse#2]
I touched on this in the Reddit comments and in another issue, but figured I'd formalise it.

* https://github.com/krisajenkins/yesql allows multiple queries per file
* Being able to do this would be extremely useful.
* You could set the "name" for each query (which could be a map key) in the file - e.g. (adapted from the yesql README)

```sql
-- name: usersByCountry
-- Counts the users in a given country.
SELECT count(*) AS count
FROM user
WHERE country_code = :country_code

-- name: userCount
-- Counts all the users.
SELECT count(*) AS count
FROM user
```

Users could then call `db.Query(userCount)` directly. A method like `ps.ParseAll("multiple_query_file.sql")` would be one approach. This would help when an application has 20+ SQL queries and you want to avoid maintaining multiple files, and instead split them by table (i.e. `user_queries.sql`, etc.)

**Comment by smotes** [comment]
This is a cool idea, but I'm not convinced on what is really to be gained here. As it stands now, you can essentially achieve the same thing by organizing queries into different files and even sub-directories if you wanted to group files by table (for example, have multiple instances of `Purse`, one per table directory). I don't want to abandon the notion of splitting things up into different files, and I also think supporting both features would just add complexity and potential confusion. I guess it's kind of like the old Perl "There's more than one way to do it" motto, which is an idea that doesn't fit well in the Go ecosystem in my opinion.
