### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by jney** [smotes/purse#6]
does the `sql` files handle parameters like [massive](https://github.com/robconery/massive-js/) does ?

**Comment by elithrar** [comment]
Based on http://massive-js.readthedocs.io/en/latest/functions/ - how would
you expect that to work?

**Comment by jney** [comment]
i'm actually talking about the `sql` call itself, ie:

`./sql/query_post_by_id.sql`

```sql
SELECT
  id, slug, title, created, markdown, html
FROM
  post
WHERE
  id=$1
;
```

```go
// Load all SQL files from specified directory into a map
ps, err := purse.New(filepath.Join(".", "sql"))

// Get a file's contents
contents, ok := ps.Get("query_post_by_id.sql")
if !ok {
    fmt.Println("SQL file not loaded")
}

// Open the database handler
db, err := sql.Open("postgres", "...")

// set the id
id := 1

// Query directly via the database handler
rows, err := db.Query(contents, [id])

// Prepare statements via the database handler
stmt, err := db.Prepare(contents, [id])
```

maybe it is already managed, but i don't see it in the documentation

**Comment by smotes** [comment]
The way `"database/sql" handles parameters is dependent on the sql driver. In the example I provided, I used PostgreSQL, so I used the `"lib/pq" driver library. In that, it takes the $<digit> style parameters, whereas others use the ? style.

**Comment by smotes** [comment]
How parameters on SQL statements are handled is out of the scope of this library, but in general it depends on the DBMS you're using.

The way "database/sql" handles parameters is dependent on the specific DBMS driver. In the example I provided in the READMD I used PostgreSQL, so I used the "lib/pq" driver library. In that, it takes the $digit style parameters, whereas others use the ? style.
